// <auto-generated />
using Courses.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Courses.DAL.Migrations
{
    [DbContext(typeof(CoursesDbContext))]
    [Migration("20250501102702_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Courses.DAL.Data.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 101,
                            Description = "Field of study that deals with the principles of business, management, and economics. It combines elements of accountancy, finance, marketing, organizational studies, human resource management, and operations.",
                            Name = "Business"
                        },
                        new
                        {
                            CourseId = 2,
                            Description = "Sales course covers a wide range of topics essential for developing effective selling skills. These include understanding the sales process, prospecting and lead generation, and building customer relationships.",
                            Name = "Sales"
                        },
                        new
                        {
                            CourseId = 3,
                            Description = "An examination of managerial decision-making and problem-solving using the marketing mix and the activities it entails such as selling, advertising, pricing, consumer behavior, marketing research and channels of distribution.",
                            Name = "Marketing"
                        },
                        new
                        {
                            CourseId = 4,
                            Description = "The course is designed to teach the theoretical and practical aspects of computing, including programming, algorithms, data structures, software development, and computer systems.",
                            Name = "Computer science"
                        },
                        new
                        {
                            CourseId = 5,
                            Description = "Hospitality, culinary arts, catering, events, human resources, marketing, sales, and finance.",
                            Name = "Hospitality"
                        },
                        new
                        {
                            CourseId = 6,
                            Description = "Combines a mixture of theoretical and practical course elements to nurture students in developing their own artistic work.",
                            Name = "Arts"
                        });
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 101,
                            FirstName = "Elijah",
                            GroupId = 101,
                            LastName = "Hall"
                        },
                        new
                        {
                            StudentId = 2,
                            FirstName = "Ethan",
                            GroupId = 101,
                            LastName = "Anderson"
                        },
                        new
                        {
                            StudentId = 3,
                            FirstName = "Olivia",
                            GroupId = 101,
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 4,
                            FirstName = "Liam",
                            GroupId = 101,
                            LastName = "Campbell"
                        },
                        new
                        {
                            StudentId = 5,
                            FirstName = "Ava",
                            GroupId = 101,
                            LastName = "Carter"
                        },
                        new
                        {
                            StudentId = 6,
                            FirstName = "Noah",
                            GroupId = 101,
                            LastName = "Clark"
                        },
                        new
                        {
                            StudentId = 7,
                            FirstName = "Sophia",
                            GroupId = 101,
                            LastName = "Davis"
                        },
                        new
                        {
                            StudentId = 8,
                            FirstName = "Mason",
                            GroupId = 101,
                            LastName = "Edwards"
                        },
                        new
                        {
                            StudentId = 9,
                            FirstName = "Isabella",
                            GroupId = 101,
                            LastName = "Evans"
                        },
                        new
                        {
                            StudentId = 10,
                            FirstName = "Lucas",
                            GroupId = 101,
                            LastName = "Foster"
                        },
                        new
                        {
                            StudentId = 11,
                            FirstName = "Mia",
                            GroupId = 2,
                            LastName = "Garcia"
                        },
                        new
                        {
                            StudentId = 12,
                            FirstName = "Benjamin",
                            GroupId = 2,
                            LastName = "Gray"
                        },
                        new
                        {
                            StudentId = 13,
                            FirstName = "Amelia",
                            GroupId = 2,
                            LastName = "Green"
                        },
                        new
                        {
                            StudentId = 14,
                            FirstName = "Elijah",
                            GroupId = 2,
                            LastName = "Hall"
                        },
                        new
                        {
                            StudentId = 15,
                            FirstName = "Charlotte",
                            GroupId = 2,
                            LastName = "Harris"
                        },
                        new
                        {
                            StudentId = 16,
                            FirstName = "Alexander",
                            GroupId = 2,
                            LastName = "Hill"
                        },
                        new
                        {
                            StudentId = 17,
                            FirstName = "Harper",
                            GroupId = 2,
                            LastName = "Hughes"
                        },
                        new
                        {
                            StudentId = 18,
                            FirstName = "James",
                            GroupId = 2,
                            LastName = "Jackson"
                        },
                        new
                        {
                            StudentId = 19,
                            FirstName = "Evelyn",
                            GroupId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 20,
                            FirstName = "William",
                            GroupId = 2,
                            LastName = "Jones"
                        },
                        new
                        {
                            StudentId = 21,
                            FirstName = "Abigail",
                            GroupId = 2,
                            LastName = "Kelly"
                        },
                        new
                        {
                            StudentId = 22,
                            FirstName = "Logan",
                            GroupId = 2,
                            LastName = "Lewis"
                        },
                        new
                        {
                            StudentId = 23,
                            FirstName = "Emily",
                            GroupId = 101,
                            LastName = "Lopez"
                        },
                        new
                        {
                            StudentId = 24,
                            FirstName = "Jacob",
                            GroupId = 101,
                            LastName = "Martin"
                        },
                        new
                        {
                            StudentId = 25,
                            FirstName = "Lily",
                            GroupId = 3,
                            LastName = "Martinez"
                        },
                        new
                        {
                            StudentId = 26,
                            FirstName = "Michael",
                            GroupId = 3,
                            LastName = "Miller"
                        },
                        new
                        {
                            StudentId = 27,
                            FirstName = "Grace",
                            GroupId = 3,
                            LastName = "Mitchell"
                        },
                        new
                        {
                            StudentId = 28,
                            FirstName = "Daniel",
                            GroupId = 3,
                            LastName = "Moore"
                        },
                        new
                        {
                            StudentId = 29,
                            FirstName = "Chloe",
                            GroupId = 3,
                            LastName = "Nelson"
                        },
                        new
                        {
                            StudentId = 30,
                            FirstName = "Henry",
                            GroupId = 3,
                            LastName = "Parker"
                        },
                        new
                        {
                            StudentId = 31,
                            FirstName = "Zoe",
                            GroupId = 6,
                            LastName = "Perez"
                        },
                        new
                        {
                            StudentId = 32,
                            FirstName = "Matthew",
                            GroupId = 6,
                            LastName = "Phillips"
                        },
                        new
                        {
                            StudentId = 33,
                            FirstName = "Ella",
                            GroupId = 6,
                            LastName = "Powell"
                        },
                        new
                        {
                            StudentId = 34,
                            FirstName = "Jackson",
                            GroupId = 6,
                            LastName = "Roberts"
                        },
                        new
                        {
                            StudentId = 35,
                            FirstName = "Scarlett",
                            GroupId = 6,
                            LastName = "Robinson"
                        },
                        new
                        {
                            StudentId = 36,
                            FirstName = "Aiden",
                            GroupId = 6,
                            LastName = "Rodriguez"
                        },
                        new
                        {
                            StudentId = 37,
                            FirstName = "Aria",
                            GroupId = 6,
                            LastName = "Scott"
                        },
                        new
                        {
                            StudentId = 38,
                            FirstName = "Samuel",
                            GroupId = 6,
                            LastName = "Simmons"
                        },
                        new
                        {
                            StudentId = 39,
                            FirstName = "Ella",
                            GroupId = 5,
                            LastName = "Stewart"
                        },
                        new
                        {
                            StudentId = 40,
                            FirstName = "Luke",
                            GroupId = 5,
                            LastName = "Taylor"
                        },
                        new
                        {
                            StudentId = 41,
                            FirstName = "Hannah",
                            GroupId = 5,
                            LastName = "Thompson"
                        },
                        new
                        {
                            StudentId = 42,
                            FirstName = "Jack",
                            GroupId = 5,
                            LastName = "Walker"
                        },
                        new
                        {
                            StudentId = 43,
                            FirstName = "Madison",
                            GroupId = 5,
                            LastName = "White"
                        },
                        new
                        {
                            StudentId = 44,
                            FirstName = "Owen",
                            GroupId = 5,
                            LastName = "Williams"
                        },
                        new
                        {
                            StudentId = 45,
                            FirstName = "Nora",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            StudentId = 46,
                            FirstName = "Caleb",
                            GroupId = 5,
                            LastName = "Young"
                        },
                        new
                        {
                            StudentId = 47,
                            FirstName = "Emma",
                            GroupId = 4,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 48,
                            FirstName = "Liam",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 49,
                            FirstName = "Noah",
                            GroupId = 5,
                            LastName = "Williams"
                        },
                        new
                        {
                            StudentId = 50,
                            FirstName = "Ava",
                            GroupId = 5,
                            LastName = "Jones"
                        },
                        new
                        {
                            StudentId = 51,
                            FirstName = "Sophia",
                            GroupId = 8,
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 52,
                            FirstName = "Mason",
                            GroupId = 8,
                            LastName = "Davis"
                        },
                        new
                        {
                            StudentId = 53,
                            FirstName = "Isabella",
                            GroupId = 8,
                            LastName = "Miller"
                        },
                        new
                        {
                            StudentId = 54,
                            FirstName = "Ethan",
                            GroupId = 5,
                            LastName = "Wilson"
                        },
                        new
                        {
                            StudentId = 55,
                            FirstName = "Olivia",
                            GroupId = 5,
                            LastName = "Moore"
                        },
                        new
                        {
                            StudentId = 56,
                            FirstName = "Lucas",
                            GroupId = 5,
                            LastName = "Taylor"
                        },
                        new
                        {
                            StudentId = 57,
                            FirstName = "Amelia",
                            GroupId = 5,
                            LastName = "Anderson"
                        },
                        new
                        {
                            StudentId = 58,
                            FirstName = "Emma",
                            GroupId = 4,
                            LastName = "Smith"
                        },
                        new
                        {
                            StudentId = 59,
                            FirstName = "Henry",
                            GroupId = 4,
                            LastName = "Johnson"
                        },
                        new
                        {
                            StudentId = 60,
                            FirstName = "Mia",
                            GroupId = 5,
                            LastName = "Williams"
                        },
                        new
                        {
                            StudentId = 61,
                            FirstName = "James",
                            GroupId = 7,
                            LastName = "Jones"
                        },
                        new
                        {
                            StudentId = 62,
                            FirstName = "Charlotte",
                            GroupId = 7,
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 63,
                            FirstName = "Alexander",
                            GroupId = 7,
                            LastName = "Davis"
                        },
                        new
                        {
                            StudentId = 64,
                            FirstName = "Grace",
                            GroupId = 7,
                            LastName = "Miller"
                        },
                        new
                        {
                            StudentId = 65,
                            FirstName = "Benjamin",
                            GroupId = 7,
                            LastName = "Wilson"
                        },
                        new
                        {
                            StudentId = 66,
                            FirstName = "Harper",
                            GroupId = 7,
                            LastName = "Moore"
                        },
                        new
                        {
                            StudentId = 67,
                            FirstName = "Jack",
                            GroupId = 7,
                            LastName = "Taylor"
                        },
                        new
                        {
                            StudentId = 68,
                            FirstName = "Ella",
                            GroupId = 7,
                            LastName = "Brown"
                        },
                        new
                        {
                            StudentId = 69,
                            FirstName = "Samuel",
                            GroupId = 7,
                            LastName = "Davis"
                        },
                        new
                        {
                            StudentId = 70,
                            FirstName = "Scarlett",
                            GroupId = 7,
                            LastName = "Miller"
                        },
                        new
                        {
                            StudentId = 71,
                            FirstName = "Logan",
                            GroupId = 7,
                            LastName = "Wilson"
                        },
                        new
                        {
                            StudentId = 72,
                            FirstName = "Abigail",
                            GroupId = 7,
                            LastName = "Moore"
                        },
                        new
                        {
                            StudentId = 73,
                            FirstName = "Abigail",
                            GroupId = 7,
                            LastName = "Young"
                        });
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.StudentsGroup", b =>
                {
                    b.Property<int>("StudentsGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentsGroupId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentsGroupId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentsGroups");

                    b.HasData(
                        new
                        {
                            StudentsGroupId = 101,
                            CourseId = 101,
                            Name = "BR-01"
                        },
                        new
                        {
                            StudentsGroupId = 2,
                            CourseId = 101,
                            Name = "BR-02"
                        },
                        new
                        {
                            StudentsGroupId = 3,
                            CourseId = 2,
                            Name = "SR-01"
                        },
                        new
                        {
                            StudentsGroupId = 4,
                            CourseId = 4,
                            Name = "CS-01"
                        },
                        new
                        {
                            StudentsGroupId = 5,
                            CourseId = 5,
                            Name = "HP-01"
                        },
                        new
                        {
                            StudentsGroupId = 6,
                            CourseId = 6,
                            Name = "TA-01"
                        },
                        new
                        {
                            StudentsGroupId = 7,
                            CourseId = 6,
                            Name = "TA-02"
                        },
                        new
                        {
                            StudentsGroupId = 8,
                            CourseId = 3,
                            Name = "M-01"
                        },
                        new
                        {
                            StudentsGroupId = 9,
                            CourseId = 3,
                            Name = "M-02"
                        });
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.Student", b =>
                {
                    b.HasOne("Courses.DAL.Data.Entities.StudentsGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.StudentsGroup", b =>
                {
                    b.HasOne("Courses.DAL.Data.Entities.Course", "Course")
                        .WithMany("StudentsGroups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.Course", b =>
                {
                    b.Navigation("StudentsGroups");
                });

            modelBuilder.Entity("Courses.DAL.Data.Entities.StudentsGroup", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
